builds:
  0f6416d5-e0d0-4bfe-65d9-0dca5df7a6f5:
    version: 1.11.0
  12847907-76e7-4f53-7cf0-c08a18d9b041:
    version: 1.1.0
  2ce21c55-4e00-4d07-5c89-ad8f2fbef82e:
    version: 1.7.0
  657abe0c-2f1b-4b58-523f-65e2e1dd623c:
    version: 1.9.0
  7a3987b0-baf9-43cf-50c0-e0a34b0a05e1:
    version: 1.3.0
  a7da083c-4938-4473-54da-1938ec74dd40:
    version: 1.2.0
  b7a7b72c-3525-4fcd-752c-c52580a20dd9:
    version: 1.8.0
  c9d1190d-1f4c-4d07-6501-fcf6adf6c779:
    version: 1.0.0
  e0d84b36-e92b-4139-56de-bc5610139f61:
    version: 1.10.0
  e1b378fd-b9b4-4ec0-6d75-0bdb7d760d47:
    version: 1.12.0
  e328d359-f2b6-4bbd-4eea-288c62da0fa8:
    version: 1.4.0
  ee427aa3-5ebe-44c2-4be4-41fe9f70d008:
    version: 1.5.0
  f6f09f78-bf18-4d0b-6391-fb4c4edd8f6a:
    version: 1.6.0
format-version: "2"
